language: android
android:
  components:
    - build-tools-26.0.2
    - android-26
    - extra
before_install:
    - yes | sdkmanager "platforms;android-27"
    - yes | sdkmanager "build-tools;28.0.3"
